// "use client";
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { throttle, handleScrollAnimation } from "@/utils/script";
import { useEffect } from "react";

const fira = Fira_Code({ subsets: ["latin"], variable: "--font--firacode" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={fira.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
